// Generated by https://quicktype.io
using Newtonsoft.Json;

namespace BlazorMovieDB.Models;

public class MovieResults : IMediaResults
{
    [JsonProperty("page")]
    public long Page { get; set; }

    [JsonProperty("results")]
    public List<Movie> Results { get; set; } = [];

    [JsonProperty("total_pages")]
    public long TotalPages { get; set; }

    [JsonProperty("total_results")]
    public long TotalResults { get; set; }
}

public class Movie : IMedia
{
    [JsonProperty("adult")]
    public bool Adult { get; set; }

    [JsonProperty("backdrop_path")] public string BackdropPath { get; set; } = null!;

    [JsonProperty("genre_ids")] public List<long> GenreIds { get; set; } = [];

    [JsonProperty("id")]
    public long Id { get; set; }

    [JsonProperty("original_language")]
    public string OriginalLanguage { get; set; } = null!;

    [JsonProperty("original_title")]
    public string? OriginalTitle { get; set; }

    [JsonProperty("overview")] public string Overview { get; set; } = null!;

    [JsonProperty("popularity")]
    public double Popularity { get; set; }

    [JsonProperty("poster_path")] public string PosterPath { get; set; } = null!;

    [JsonProperty("release_date")]
    public DateTimeOffset ReleaseDate { get; set; }

    [JsonProperty("title")]
    public string? Title { get; set; }

    [JsonProperty("video")]
    public bool Video { get; set; }

    [JsonProperty("vote_average")]
    public double VoteAverage { get; set; }

    [JsonProperty("vote_count")]
    public long VoteCount { get; set; }
}

